//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSFWSoftSolutions
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceItem
    {
        public long InvoiceItemID { get; set; }
        public long InvoiceID { get; set; }
        public Nullable<int> InvID { get; set; }
        public int Rate { get; set; }
        public int Quantity { get; set; }
        public string ItemDescription { get; set; }
        public int TotalAmount { get; set; }
        public Nullable<long> SizeID { get; set; }
    
        public virtual InvoiceDetail InvoiceDetail { get; set; }
        public virtual Item Item { get; set; }
        public virtual ItemSize ItemSize { get; set; }
    }
}
