//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSFWSoftSolutions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.InvoiceItems = new HashSet<InvoiceItem>();
        }
    
        public int InvID { get; set; }
        public string ICode { get; set; }
        public string HSN { get; set; }
        public string Description { get; set; }
        public int TypeID { get; set; }
        public int ColorID { get; set; }
        public int BrandID { get; set; }
        public int AvailableUnits { get; set; }
        public int CostPrice { get; set; }
        public int SellingPrice { get; set; }
        public int LastSellingPrice { get; set; }
        public System.DateTime DateOfEntry { get; set; }
        public string Rack { get; set; }
        public string BatchNumber { get; set; }
        public bool IsSaleDiscount { get; set; }
        public int SaleDiscountP { get; set; }
        public System.DateTime DateOfPurchase { get; set; }
        public Nullable<System.DateTime> DateOfEntryNew { get; set; }
    
        public virtual BrandType BrandType { get; set; }
        public virtual ColourType ColourType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceItem> InvoiceItems { get; set; }
        public virtual ItemType ItemType { get; set; }
    }
}
