//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int InvID { get; set; }
        public string ICode { get; set; }
        public string HSN { get; set; }
        public string Description { get; set; }
        public int TypeID { get; set; }
        public int ColorID { get; set; }
        public int BrandID { get; set; }
        public int AvailableUnits { get; set; }
        public int CostPrice { get; set; }
        public int SellingPrice { get; set; }
        public int MaxDiscount { get; set; }
        public System.DateTime DateOfPurchase { get; set; }
        public System.DateTime DateOfEntry { get; set; }
        public string Rack { get; set; }
        public string BatchNumber { get; set; }
    
        public virtual BrandType BrandType { get; set; }
        public virtual ColourType ColourType { get; set; }
        public virtual ItemType ItemType { get; set; }
    }
}
